parameters:
  pool: ''

jobs:
- job: linux
  container: nv-wasm

  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget

  steps:
  - checkout: self
    clean: true
  
  - bash: |
      sudo chmod -R 777 /emsdk
      cd /emsdk
      sudo ./emsdk activate sdk-1.38.31-64bit

    displayName: 'Setup Emscripten'

  - task: GitVersion@4
    inputs:
      updateAssemblyInfo: false

  - script: |
      source /emsdk/emsdk_env.sh
      msbuild /r /p:Configuration=Release "/p:PackageVersion=$(GITVERSION_FullSemVer)" $(build.sourcesdirectory)/NetliftDemo/NetliftDemo.Wasm/NetliftDemo.Wasm.csproj

    env:
      GITVERSION_FullSemVer: $(GITVERSION_FullSemVer)

  - task: CopyFiles@2
    displayName: 'Publish Wasm Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/NetliftDemo/NetliftDemo.Wasm/bin/Release/netstandard2.0/dist
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)/Uno-Lottie-wasm
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: NetliftDemo-Aot-drop
      ArtifactType: Container
